const PRODUCTS = [
  {
    id: "six-star-testosterone",
    name: "Six Star Testosterone Booster",
    category: "homme",
    categoryLabel: "Homme",
    price: 28900,
    badge: "Nouveau",
    image: "img/02f12830-0345-4693-ae9d-32c823700184.jpeg",
    short: "Booster de testostérone — force, énergie et résultats dès 7 jours.",
    desc: "Formule avancée à la rhodiola (385 mg), citrate de bore, vitamine D3 et zinc. Conçue pour les hommes actifs qui veulent plus de force, de masse musculaire et de vitalité.",
    benefits: [
      "Soutient la testostérone naturellement",
      "Développe force et masse musculaire",
      "Boost énergie, endurance et libido",
      "60 caplets — 2 par jour",
    ],
  },
  {
    id: "libido-max",
    name: "Libido-Max for Active Men",
    category: "homme",
    categoryLabel: "Homme",
    price: 26900,
    badge: "Nouveau",
    image: "img/581c6157-75c6-49aa-accb-45066a1838d7.jpeg",
    short: "Énergie, vitalité et performance pour les hommes actifs.",
    desc: "Formule naturelle Irwin Naturals à la maca, ginseng rouge, ashwagandha et L-arginine. Révèle le meilleur de vous-même : endurance, libido et soutien hormonal.",
    benefits: [
      "Combat la fatigue et booste l'endurance",
      "Soutient libido et performance",
      "Favorise des niveaux sains de testostérone",
      "2 soft-gels par jour avec un repas",
    ],
  },
  {
    id: "naturade-weight-gain",
    name: "Naturade Weight Gain Vanille",
    category: "energie",
    categoryLabel: "Énergie",
    price: 32900,
    badge: "Nouveau",
    image: "img/94edf20d-befc-45cb-b4df-1218793798a5.jpeg",
    short: "Gainer vanille — jusqu'à 1600 calories pour une prise de masse saine.",
    desc: "Gainer naturellement aromatisé à la vanille. Idéal pour sportifs, prise de masse et courbes plus fermes. Riche en protéines, vitamines et minéraux, sans gluten.",
    benefits: [
      "Prise de masse musculaire",
      "Apport énergétique élevé",
      "Récupération après l'effort",
      "Goût vanille délicieux",
    ],
  },
  {
    id: "evl-cla1000",
    name: "EVL CLA1000",
    category: "energie",
    categoryLabel: "Énergie",
    price: 21900,
    badge: "Nouveau",
    image: "img/a5976641-7da3-4276-b214-64dfc42e55b4.jpeg",
    short: "Soutien minceur et définition musculaire — 90 softgels.",
    desc: "Formule CLA sans stimulant pour gérer le poids, soutenir le métabolisme et favoriser une composition corporelle plus sèche. Idéal pour hommes et femmes actifs.",
    benefits: [
      "Soutient le métabolisme",
      "Aide à la gestion du poids",
      "Favorise la masse maigre",
      "Sans gluten — 1 à 3 softgels / jour",
    ],
  },
  {
    id: "one-a-day-men-50",
    name: "One A Day Men's 50+ Gummy",
    category: "homme",
    categoryLabel: "Homme",
    price: 18900,
    badge: "Nouveau",
    image: "img/da5a4021-caeb-4a3b-94f9-704244d6a2a7.jpeg",
    short: "Multivitamines gummies fraise — soutien complet après 50 ans.",
    desc: "Le soutien nutritionnel quotidien pour les hommes de 50 ans et plus. 12 vitamines essentielles, 8 minéraux clés, goût fraise, sans colorants artificiels.",
    benefits: [
      "Immunité, cœur et énergie",
      "Soutien cognitif et musculaire",
      "Os et articulations",
      "110 gummies — 55 jours",
    ],
  },
  {
    id: "dr-murray-protein",
    name: "Dr Murray 3 Seed Protein",
    category: "energie",
    categoryLabel: "Énergie",
    price: 24900,
    badge: "Nouveau",
    image: "img/ee85714d-768a-4b1a-b1c3-1a171c8b9a11.jpeg",
    short: "Protéine végétale 3 graines — 18 g de protéines, 100 % vegan.",
    desc: "Poudre unflavored à base de courge, tournesol et lin. 18 g de protéines, 0 g de sucre, keto friendly. Alimentez vos performances avec une formule facile à digérer.",
    benefits: [
      "Développe et maintient la masse musculaire",
      "100 % végétal, sans soja ni OGM",
      "Énergie durable, facile à digérer",
      "16 portions par sachet",
    ],
  },
  {
    id: "purera",
    name: "Purera Gluta Collagen+",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 24900,
    badge: "Best-seller",
    image: "img/4d1e0ec4-a5ce-4c1a-a3e0-617f091b615a (1).jpeg",
    short: "Collagène fraise & Vit C pour une peau claire, douce et éclatante.",
    desc: "Boisson collagène à la fraise enrichie en glutathion et vitamine C. Aide à révéler une peau plus lumineuse, ferme et hydratée de l'intérieur.",
    benefits: [
      "Peau éclatante et uniforme",
      "Fermeté & élasticité",
      "Hydratation intense",
      "Antioxydant puissant",
    ],
  },
  {
    id: "beauty-milk-melon",
    name: "Beauty Milk Melon",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 22900,
    image: "img/f8d74968-cfa2-4338-9abc-8c8cd485d230.jpeg",
    short: "Boisson collagène melon japonais — 50 000 mg pour éclat & hydratation.",
    desc: "Premium Japanese Melon Collagen Drink. Une boisson gourmande enrichie en collagène, acide hyaluronique et vitamine C pour une peau lumineuse.",
    benefits: [
      "Éclat & luminosité",
      "Hydratation intense",
      "Fermeté & élasticité",
      "Goût melon rafraîchissant",
    ],
  },
  {
    id: "beauty-milk-ichigo",
    name: "Beauty Milk Ichigo",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 22900,
    image: "img/7d1d305b-b4c1-4751-8b52-b00d8084e652.jpeg",
    short: "Milkshake fraise japonaise au glutathion pour un teint lumineux.",
    desc: "Premium Japanese Strawberry Glutathione Drink. Révèle votre éclat naturel grâce au glutathion, collagène et vitamine C.",
    benefits: [
      "Éclaircit & unifie le teint",
      "Hydrate & nourrit",
      "Antioxydant puissant",
      "Délicieux goût fraise",
    ],
  },
  {
    id: "beauty-milk-fraise",
    name: "Beauty Milk Strawberry",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 21900,
    image: "img/93ef0a66-350c-4475-b254-0b633ce0d234.jpeg",
    short: "Boisson glutathione fraise pour une peau hydratée et uniforme.",
    desc: "Formule glutathion à la fraise japonaise pour éclaircir, hydrater et protéger la peau au quotidien.",
    benefits: [
      "Teint plus clair",
      "Hydratation profonde",
      "Protection antioxydante",
      "Routine 1× par jour",
    ],
  },
  {
    id: "collagen-gummies",
    name: "Collagen Peptides Gummies",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 18900,
    image: "img/aaa9d1f1-5af5-46c1-a278-2e1a351dbef6.jpeg",
    short: "Gummies collagène type 1+3 au goût fraise — beauté, force, confiance.",
    desc: "Des gummies délicieux enrichis en peptides de collagène pour soutenir peau, cheveux, ongles et articulations.",
    benefits: [
      "Peau éclatante et ferme",
      "Cheveux forts et brillants",
      "Ongles sains",
      "Soutien articulaire",
    ],
  },
  {
    id: "hair-skin-nails",
    name: "Ultra Hair, Skin & Nails",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 16900,
    image: "img/220e7462-b007-4777-9285-c3b948a8e717.jpeg",
    short: "Formule biotine pour cheveux plus forts, peau éclatante et ongles sains.",
    desc: "Complément avancé à la biotine. Beauté qui commence de l'intérieur — sans OGM, sans gluten, sans colorants artificiels.",
    benefits: [
      "Cheveux plus forts",
      "Peau éclatante",
      "Ongles en santé",
      "Formule propre",
    ],
  },
  {
    id: "collagen-chocolate",
    name: "Collagen Peptides Chocolat",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 27900,
    image: "img/54ac33a7-86e5-4b3e-bd07-bfb1656bb0f4.jpeg",
    short: "20 g de collagène hydrolysé par portion — goût chocolat irrésistible.",
    desc: "Peptides de collagène type I & III pour soutenir cheveux, peau, ongles et articulations. Saveur chocolat naturelle.",
    benefits: [
      "Élasticité de la peau",
      "Cheveux renforcés",
      "Ongles plus résistants",
      "Soutien articulaire",
    ],
  },
  {
    id: "g-curve",
    name: "G-Curve",
    category: "femme",
    categoryLabel: "Femme",
    price: 25900,
    badge: "Populaire",
    image: "img/5c81c1c3-f03e-49fa-b059-f7c1fda99b7f.jpeg",
    short: "Formule avancée pour soutenir féminité et courbes naturelles.",
    desc: "Confiance. Courbes. Vous. Une formule à base de plantes conçue pour les femmes qui veulent sublimer leurs formes avec élégance.",
    benefits: [
      "Soutient fermeté & volume",
      "Favorise des courbes naturelles",
      "Peau lisse et éclatante",
      "Boost de confiance",
    ],
  },
  {
    id: "raising-hips",
    name: "Raising Hips",
    category: "femme",
    categoryLabel: "Femme",
    price: 26900,
    image: "img/1688010b-e634-411e-95d9-c9a473c4f46f.jpeg",
    short: "Des hanches plus fermes, plus rondes et plus attrayantes.",
    desc: "Supplément ciblé pour augmenter le volume des hanches, sculpter les courbes et raffermir la peau. Formule naturelle.",
    benefits: [
      "Augmente le volume des hanches",
      "Sculpte des courbes naturelles",
      "Raffermit et tonifie",
      "Améliore l'élasticité",
    ],
  },
  {
    id: "vitaform-men",
    name: "Vitaform for Men",
    category: "homme",
    categoryLabel: "Homme",
    price: 19900,
    image: "img/283cd874-c5fb-4297-ac3e-a53ca2fefff9.jpeg",
    short: "Multivitamines pour hommes actifs — énergie, immunité, performance.",
    desc: "Multi's made simple. 2 comprimés par jour avec un repas. 100 % des nutriments essentiels et 6 complexes fonctionnels.",
    benefits: [
      "Santé immunitaire",
      "Énergie & vitalité",
      "Performance & endurance",
      "Santé masculine",
    ],
  },
  {
    id: "peruvian-maca",
    name: "Peruvian Maca",
    category: "homme",
    categoryLabel: "Homme",
    price: 17900,
    image: "img/222e5310-9de7-4162-8007-5010081c9a78.jpeg",
    short: "Énergie naturelle, force et vitalité — pour hommes et femmes.",
    desc: "Maca péruvienne premium. Soutient l'endurance, la force musculaire et la vitalité au quotidien.",
    benefits: [
      "Énergie & endurance",
      "Force & masse musculaire",
      "Vitalité naturelle",
      "Ingrédient de qualité",
    ],
  },
  {
    id: "ginger-rescue",
    name: "Ginger Rescue Energy",
    category: "energie",
    categoryLabel: "Énergie",
    price: 12900,
    image: "img/1200b0d7-59b1-4500-b7bd-323b63b9f0fd.jpeg",
    short: "Shot gingembre citron cayenne — boost naturel sans caféine.",
    desc: "Votre coup de boost naturel au gingembre. Énergie propre, soutien immunitaire et digestion facilitée.",
    benefits: [
      "Énergie naturelle",
      "Soutien immunitaire",
      "Favorise la digestion",
      "Sans caféine",
    ],
  },
  {
    id: "zoo-friends",
    name: "Zoo Friends Extra C",
    category: "enfants",
    categoryLabel: "Enfants",
    price: 14900,
    image: "img/3c95db89-012e-454a-a749-889376ed934f.jpeg",
    short: "Multivitamines à croquer pour enfants heureux et en pleine forme.",
    desc: "Le soutien quotidien pour grandir fort et en bonne santé. Goût orange naturel, forme animaux amusante.",
    benefits: [
      "Soutient l'immunité",
      "Énergie & vitalité",
      "Ingrédients de qualité",
      "Goût orange naturel",
    ],
  },
];
