const FALLBACK_PRODUCTS = [
  {
    id: "six-star-testosterone",
    name: "Six Star Testosterone Booster",
    category: "homme",
    categoryLabel: "Homme",
    price: 28900,
    badge: "Nouveau",
    image: "img/02f12830-0345-4693-ae9d-32c823700184.jpeg",
    short: "Booster de testostérone — force, énergie et résultats dès 7 jours.",
    desc: "Formule avancée à la rhodiola (385 mg), citrate de bore, vitamine D3 et zinc. Conçue pour les hommes actifs qui veulent plus de force, de masse musculaire et de vitalité.",
    benefits: [
      "Soutient la testostérone naturellement",
      "Développe force et masse musculaire",
      "Boost énergie, endurance et libido",
      "60 caplets — 2 par jour",
    ],
  },
  {
    id: "libido-max",
    name: "Libido-Max for Active Men",
    category: "homme",
    categoryLabel: "Homme",
    price: 26900,
    badge: "Nouveau",
    image: "img/581c6157-75c6-49aa-accb-45066a1838d7.jpeg",
    short: "Énergie, vitalité et performance pour les hommes actifs.",
    desc: "Formule naturelle Irwin Naturals à la maca, ginseng rouge, ashwagandha et L-arginine. Révèle le meilleur de vous-même : endurance, libido et soutien hormonal.",
    benefits: [
      "Combat la fatigue et booste l'endurance",
      "Soutient libido et performance",
      "Favorise des niveaux sains de testostérone",
      "2 soft-gels par jour avec un repas",
    ],
  },
  {
    id: "naturade-weight-gain",
    name: "Naturade Weight Gain Vanille",
    category: "energie",
    categoryLabel: "Énergie",
    price: 32900,
    badge: "Nouveau",
    image: "img/94edf20d-befc-45cb-b4df-1218793798a5.jpeg",
    short: "Gainer vanille — jusqu'à 1600 calories pour une prise de masse saine.",
    desc: "Gainer naturellement aromatisé à la vanille. Idéal pour sportifs, prise de masse et courbes plus fermes. Riche en protéines, vitamines et minéraux, sans gluten.",
    benefits: [
      "Prise de masse musculaire",
      "Apport énergétique élevé",
      "Récupération après l'effort",
      "Goût vanille délicieux",
    ],
  },
  {
    id: "evl-cla1000",
    name: "EVL CLA1000",
    category: "energie",
    categoryLabel: "Énergie",
    price: 21900,
    badge: "Nouveau",
    image: "img/a5976641-7da3-4276-b214-64dfc42e55b4.jpeg",
    short: "Soutien minceur et définition musculaire — 90 softgels.",
    desc: "Formule CLA sans stimulant pour gérer le poids, soutenir le métabolisme et favoriser une composition corporelle plus sèche. Idéal pour hommes et femmes actifs.",
    benefits: [
      "Soutient le métabolisme",
      "Aide à la gestion du poids",
      "Favorise la masse maigre",
      "Sans gluten — 1 à 3 softgels / jour",
    ],
  },
  {
    id: "one-a-day-men-50",
    name: "One A Day Men's 50+ Gummy",
    category: "homme",
    categoryLabel: "Homme",
    price: 18900,
    badge: "Nouveau",
    image: "img/da5a4021-caeb-4a3b-94f9-704244d6a2a7.jpeg",
    short: "Multivitamines gummies fraise — soutien complet après 50 ans.",
    desc: "Le soutien nutritionnel quotidien pour les hommes de 50 ans et plus. 12 vitamines essentielles, 8 minéraux clés, goût fraise, sans colorants artificiels.",
    benefits: [
      "Immunité, cœur et énergie",
      "Soutien cognitif et musculaire",
      "Os et articulations",
      "110 gummies — 55 jours",
    ],
  },
  {
    id: "dr-murray-protein",
    name: "Dr Murray 3 Seed Protein",
    category: "energie",
    categoryLabel: "Énergie",
    price: 24900,
    badge: "Nouveau",
    image: "img/ee85714d-768a-4b1a-b1c3-1a171c8b9a11.jpeg",
    short: "Protéine végétale 3 graines — 18 g de protéines, 100 % vegan.",
    desc: "Poudre unflavored à base de courge, tournesol et lin. 18 g de protéines, 0 g de sucre, keto friendly. Alimentez vos performances avec une formule facile à digérer.",
    benefits: [
      "Développe et maintient la masse musculaire",
      "100 % végétal, sans soja ni OGM",
      "Énergie durable, facile à digérer",
      "16 portions par sachet",
    ],
  },
  {
    id: "purera",
    name: "Purera Gluta Collagen+",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 24900,
    badge: "Best-seller",
    image: "img/4d1e0ec4-a5ce-4c1a-a3e0-617f091b615a (1).jpeg",
    short: "Collagène fraise & Vit C pour une peau claire, douce et éclatante.",
    desc: "Boisson collagène à la fraise enrichie en glutathion et vitamine C. Aide à révéler une peau plus lumineuse, ferme et hydratée de l'intérieur.",
    benefits: [
      "Peau éclatante et uniforme",
      "Fermeté & élasticité",
      "Hydratation intense",
      "Antioxydant puissant",
    ],
  },
  {
    id: "beauty-milk-melon",
    name: "Beauty Milk Melon",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 22900,
    image: "img/f8d74968-cfa2-4338-9abc-8c8cd485d230.jpeg",
    short: "Boisson collagène melon japonais — 50 000 mg pour éclat & hydratation.",
    desc: "Premium Japanese Melon Collagen Drink. Une boisson gourmande enrichie en collagène, acide hyaluronique et vitamine C pour une peau lumineuse.",
    benefits: [
      "Éclat & luminosité",
      "Hydratation intense",
      "Fermeté & élasticité",
      "Goût melon rafraîchissant",
    ],
  },
  {
    id: "beauty-milk-ichigo",
    name: "Beauty Milk Ichigo",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 22900,
    image: "img/7d1d305b-b4c1-4751-8b52-b00d8084e652.jpeg",
    short: "Milkshake fraise japonaise au glutathion pour un teint lumineux.",
    desc: "Premium Japanese Strawberry Glutathione Drink. Révèle votre éclat naturel grâce au glutathion, collagène et vitamine C.",
    benefits: [
      "Éclaircit & unifie le teint",
      "Hydrate & nourrit",
      "Antioxydant puissant",
      "Délicieux goût fraise",
    ],
  },
  {
    id: "beauty-milk-fraise",
    name: "Beauty Milk Strawberry",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 21900,
    image: "img/93ef0a66-350c-4475-b254-0b633ce0d234.jpeg",
    short: "Boisson glutathione fraise pour une peau hydratée et uniforme.",
    desc: "Formule glutathion à la fraise japonaise pour éclaircir, hydrater et protéger la peau au quotidien.",
    benefits: [
      "Teint plus clair",
      "Hydratation profonde",
      "Protection antioxydante",
      "Routine 1× par jour",
    ],
  },
  {
    id: "collagen-gummies",
    name: "Collagen Peptides Gummies",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 18900,
    image: "img/aaa9d1f1-5af5-46c1-a278-2e1a351dbef6.jpeg",
    short: "Gummies collagène type 1+3 au goût fraise — beauté, force, confiance.",
    desc: "Des gummies délicieux enrichis en peptides de collagène pour soutenir peau, cheveux, ongles et articulations.",
    benefits: [
      "Peau éclatante et ferme",
      "Cheveux forts et brillants",
      "Ongles sains",
      "Soutien articulaire",
    ],
  },
  {
    id: "hair-skin-nails",
    name: "Ultra Hair, Skin & Nails",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 16900,
    image: "img/220e7462-b007-4777-9285-c3b948a8e717.jpeg",
    short: "Formule biotine pour cheveux plus forts, peau éclatante et ongles sains.",
    desc: "Complément avancé à la biotine. Beauté qui commence de l'intérieur — sans OGM, sans gluten, sans colorants artificiels.",
    benefits: [
      "Cheveux plus forts",
      "Peau éclatante",
      "Ongles en santé",
      "Formule propre",
    ],
  },
  {
    id: "collagen-chocolate",
    name: "Collagen Peptides Chocolat",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 27900,
    image: "img/54ac33a7-86e5-4b3e-bd07-bfb1656bb0f4.jpeg",
    short: "20 g de collagène hydrolysé par portion — goût chocolat irrésistible.",
    desc: "Peptides de collagène type I & III pour soutenir cheveux, peau, ongles et articulations. Saveur chocolat naturelle.",
    benefits: [
      "Élasticité de la peau",
      "Cheveux renforcés",
      "Ongles plus résistants",
      "Soutien articulaire",
    ],
  },
  {
    id: "g-curve",
    name: "G-Curve",
    category: "femme",
    categoryLabel: "Femme",
    price: 25900,
    badge: "Populaire",
    image: "img/5c81c1c3-f03e-49fa-b059-f7c1fda99b7f.jpeg",
    short: "Formule avancée pour soutenir féminité et courbes naturelles.",
    desc: "Confiance. Courbes. Vous. Une formule à base de plantes conçue pour les femmes qui veulent sublimer leurs formes avec élégance.",
    benefits: [
      "Soutient fermeté & volume",
      "Favorise des courbes naturelles",
      "Peau lisse et éclatante",
      "Boost de confiance",
    ],
  },
  {
    id: "raising-hips",
    name: "Raising Hips",
    category: "femme",
    categoryLabel: "Femme",
    price: 26900,
    image: "img/1688010b-e634-411e-95d9-c9a473c4f46f.jpeg",
    short: "Des hanches plus fermes, plus rondes et plus attrayantes.",
    desc: "Supplément ciblé pour augmenter le volume des hanches, sculpter les courbes et raffermir la peau. Formule naturelle.",
    benefits: [
      "Augmente le volume des hanches",
      "Sculpte des courbes naturelles",
      "Raffermit et tonifie",
      "Améliore l'élasticité",
    ],
  },
  {
    id: "vitaform-men",
    name: "Vitaform for Men",
    category: "homme",
    categoryLabel: "Homme",
    price: 19900,
    image: "img/283cd874-c5fb-4297-ac3e-a53ca2fefff9.jpeg",
    short: "Multivitamines pour hommes actifs — énergie, immunité, performance.",
    desc: "Multi's made simple. 2 comprimés par jour avec un repas. 100 % des nutriments essentiels et 6 complexes fonctionnels.",
    benefits: [
      "Santé immunitaire",
      "Énergie & vitalité",
      "Performance & endurance",
      "Santé masculine",
    ],
  },
  {
    id: "peruvian-maca",
    name: "Peruvian Maca",
    category: "homme",
    categoryLabel: "Homme",
    price: 17900,
    image: "img/222e5310-9de7-4162-8007-5010081c9a78.jpeg",
    short: "Énergie naturelle, force et vitalité — pour hommes et femmes.",
    desc: "Maca péruvienne premium. Soutient l'endurance, la force musculaire et la vitalité au quotidien.",
    benefits: [
      "Énergie & endurance",
      "Force & masse musculaire",
      "Vitalité naturelle",
      "Ingrédient de qualité",
    ],
  },
  {
    id: "ginger-rescue",
    name: "Ginger Rescue Energy",
    category: "energie",
    categoryLabel: "Énergie",
    price: 12900,
    image: "img/1200b0d7-59b1-4500-b7bd-323b63b9f0fd.jpeg",
    short: "Shot gingembre citron cayenne — boost naturel sans caféine.",
    desc: "Votre coup de boost naturel au gingembre. Énergie propre, soutien immunitaire et digestion facilitée.",
    benefits: [
      "Énergie naturelle",
      "Soutien immunitaire",
      "Favorise la digestion",
      "Sans caféine",
    ],
  },
  {
    id: "zoo-friends",
    name: "Zoo Friends Extra C",
    category: "enfants",
    categoryLabel: "Enfants",
    price: 14900,
    image: "img/3c95db89-012e-454a-a749-889376ed934f.jpeg",
    short: "Multivitamines à croquer pour enfants heureux et en pleine forme.",
    desc: "Le soutien quotidien pour grandir fort et en bonne santé. Goût orange naturel, forme animaux amusante.",
    benefits: [
      "Soutient l'immunité",
      "Énergie & vitalité",
      "Ingrédients de qualité",
      "Goût orange naturel",
    ],
  },
  {
    id: "orgain-creatine",
    name: "Orgain Creatine Monohydrate",
    category: "homme",
    categoryLabel: "Homme",
    price: 24900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-18 at 16.25.33.jpeg",
    short: "Créatine micronisée 5 g — puissance, performance et récupération.",
    desc: "100 portions de créatine monohydrate micronisée Orgain. Sans OGM, sans gluten, sans sucre ajouté. Soutient la force musculaire, la fonction cognitive et la récupération après l'effort.",
    benefits: [
      "Soutient la force et la puissance musculaire",
      "Favorise la fonction cognitive",
      "Améliore les performances physiques",
      "Aide à la récupération après l'effort",
    ],
  },
  {
    id: "dr-rashel-24k-gold",
    name: "Dr. Rashel 24K Gold Primer Serum",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 19900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-18 at 16.25.3.jpeg",
    short: "Sérum visage 24K Gold — éclat, jeunesse et fermeté.",
    desc: "Sérum primer anti-âge à l'or 24K par Dr. Rashel. Éclat immédiat, hydratation intense et régénération cellulaire pour tous types de peaux.",
    benefits: [
      "Éclat immédiat dès la première utilisation",
      "Anti-âge puissant — réduit rides et ridules",
      "Hydratation intense toute la journée",
      "Régénération cellulaire",
    ],
  },
  {
    id: "california-gold-creatine",
    name: "California Gold Nutrition Creatine",
    category: "homme",
    categoryLabel: "Homme",
    price: 22900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-18 at 16.25..jpeg",
    short: "Créatine monohydrate Sport — 5 g par portion, qualité premium.",
    desc: "Créatine monohydrate California Gold Nutrition Sport. 454 g (~90 portions). Sans gluten, sans OGM, sans soja. Soutient la force, la performance et la récupération.",
    benefits: [
      "Soutient la force et la puissance musculaire",
      "Améliore les performances physiques",
      "Favorise une récupération rapide",
      "Soutient la fonction cognitive",
    ],
  },
  {
    id: "dr-rashel-collagen-serum",
    name: "Dr. Rashel Collagen Firming Serum",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 18900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-18 at 16.2.jpeg",
    short: "Sérum collagène — raffermit, lisse et rajeunit la peau.",
    desc: "Sérum primer Dr. Rashel au collagène pour augmenter l'élasticité et la fermeté de la peau. Formule avancée, testée dermatologiquement, convient à tous types de peaux.",
    benefits: [
      "Raffermit et améliore l'élasticité",
      "Réduit les rides et ridules",
      "Rend la peau lisse et éclatante",
      "Usage quotidien — matin & soir",
    ],
  },
  {
    id: "ensure-original",
    name: "Ensure Original Nutrition Shake",
    category: "energie",
    categoryLabel: "Énergie",
    price: 34900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-19 at 08.22.05.jpeg",
    short: "Shake nutritionnel vanille — 9 g protéines, 27 vitamines & minéraux.",
    desc: "Ensure Original Nutrition Shake vanille. Nutrition complète et équilibrée avec 9 g de protéines, 220 calories et 27 vitamines & minéraux. Pack de 24 bouteilles.",
    benefits: [
      "Source de protéines de haute qualité",
      "Aide à maintenir la masse musculaire",
      "27 vitamines et minéraux essentiels",
      "Parfait en collation ou après l'entraînement",
    ],
  },
  {
    id: "premier-protein-coffeehouse",
    name: "Premier Protein Coffeehouse",
    category: "energie",
    categoryLabel: "Énergie",
    price: 36900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-19 at 08.22.07.jpeg",
    short: "Shake protéiné caramel macchiato — 30 g protéines, goût café.",
    desc: "Premier Protein Coffeehouse Caramel Macchiato. 30 g de protéines, 160 calories, 24 vitamines & minéraux, sans sucre ajouté. Pack de 12 bouteilles.",
    benefits: [
      "30 g de protéines par bouteille",
      "Seulement 160 calories",
      "24 vitamines et minéraux",
      "Délicieux goût café caramel",
    ],
  },
  {
    id: "liquid-collagen",
    name: "Applied Nutrition Liquid Collagen",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 21900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-19 at 08.22.0.jpeg",
    short: "Collagène liquide — peau, cheveux et ongles revitalisés.",
    desc: "Liquid Collagen Skin Revitalization par Applied Nutrition. Collagène hydrolysé (4000 mg), biotine (2000 mcg) et silice (6000 mcg). Saveur tropicale fraise et kiwi. 10 tubes liquides.",
    benefits: [
      "Peau éclatante et hydratée",
      "Cheveux fortifiés",
      "Ongles plus solides",
      "Seulement 25 calories par portion",
    ],
  },
  {
    id: "force-factor-tribulus",
    name: "Force Factor Tribulus Terrestris",
    category: "homme",
    categoryLabel: "Homme",
    price: 19900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-19 at 20.41.12.jpeg",
    short: "Soutien naturel testostérone — force, énergie et confiance.",
    desc: "Force Factor Fundamentals Tribulus Terrestris. Formule puissante à base d'extrait pur, absorption supérieure, sans OGM. Fabriqué aux USA. 60 capsules — 2 par jour.",
    benefits: [
      "Aide à augmenter la testostérone naturellement",
      "Absorption supérieure",
      "Ingrédients naturels",
      "Qualité premium — fabriqué aux USA",
    ],
  },
  {
    id: "sadoer-muscle-stimulator",
    name: "Sadoer Muscle Stimulator",
    category: "homme",
    categoryLabel: "Homme",
    price: 15900,
    badge: "Nouveau",
    image: "img/WhatsApp Image 2026-08-19 at 20.41.1.jpeg",
    short: "Gel crème tonifiant — sculpte et renforce la definition musculaire.",
    desc: "Sadoer Abs Muscle Stimulator Six Pack Toning Cream. Formule 6 en 1 pour brûler les graisses, augmenter la masse musculaire et tonifier le corps. 60 g — absorption rapide, sans résidu gras.",
    benefits: [
      "Brûle les graisses localement",
      "Augmente la masse musculaire",
      "Sculpte et tonifie le corps",
      "Résultats rapides et durables",
    ],
  },
  {
    id: "neocell-beauty-infusion",
    name: "NeoCell Collagen Beauty Infusion",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 24900,
    badge: "Nouveau",
    image: "img/9e7cd955-cc3e-4bf4-a9de-45b7fcf07662.jpeg",
    short: "Boisson collagène tangerine — peau, cheveux et ongles de l'intérieur.",
    desc: "NeoCell Collagen Beauty Infusion, goût Tangerine Twist. Formule avancée alliant collagène, acide hyaluronique et biotine pour une beauté qui rayonne de l'intérieur. Résultats visibles et confiance renouvelée.",
    benefits: [
      "Peau éclatante, ferme et hydratée",
      "Cheveux fortifiés et plus brillants",
      "Ongles plus résistants",
      "Soutien articulaire & bien-être global",
    ],
  },
  {
    id: "cgn-kids-vitamin-c",
    name: "California Gold Kids Vitables Vitamine C",
    category: "enfants",
    categoryLabel: "Enfants",
    price: 14900,
    badge: "Nouveau",
    image: "img/1fc55553-fd56-4014-b75f-e6f9e4002fd9.jpeg",
    short: "Comprimés à croquer goût orange — immunité & antioxydant pour enfants.",
    desc: "California Gold Nutrition Kids Vitables Chewables Vitamin C. 90 comprimés végétariens naturellement aromatisés à l'orange. Idéal dès 4 ans pour soutenir l'immunité et une peau saine.",
    benefits: [
      "Soutient le système immunitaire",
      "Antioxydant pour la santé générale",
      "Favorise une peau saine",
      "Délicieux goût d'orange — sans gélatine",
    ],
  },
  {
    id: "neocell-marine-collagen",
    name: "NeoCell Marine Collagen + Acide Hyaluronique",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 27900,
    badge: "Nouveau",
    image: "img/b031b645-2310-4b1d-ab70-3e0c5dadd967.jpeg",
    short: "Collagène marin hydrolysé — peau, cheveux, ongles et articulations.",
    desc: "NeoCell Marine Collagen Peptides + Hyaluronic Acid. 120 capsules. Collagène marin hydrolysé pour une assimilation optimale, associé à l'acide hyaluronique. Sans gluten, sans OGM.",
    benefits: [
      "Peau hydratée et élastique",
      "Cheveux plus épais et brillants",
      "Ongles moins cassants",
      "Souplesse articulaire",
    ],
  },
  {
    id: "cgn-vitamin-c-gummies",
    name: "California Gold Vitamine C Adult Gummies",
    category: "energie",
    categoryLabel: "Énergie",
    price: 16900,
    badge: "Nouveau",
    image: "img/c62a2b87-1b83-47c9-83ea-837face452c9.jpeg",
    short: "Gummies vitamine C goût orange — immunité, antioxydant et peau éclatante.",
    desc: "California Gold Nutrition Vitamin C Adult Gummies. 90 gummies végétariens au goût naturel d'orange. Sans gélatine, sans gluten, sans OGM. La vitamine C au quotidien, sous une forme gourmande.",
    benefits: [
      "Soutient le système immunitaire",
      "Antioxydant puissant",
      "Contribue à une peau lumineuse",
      "2 gummies par jour — végétarien",
    ],
  },
  {
    id: "neocell-collagen-liquid",
    name: "NeoCell Collagen Peptides Liquid Grenade",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 29900,
    badge: "Nouveau",
    image: "img/53ebf2c2-6d9c-41c1-8d92-4eff5cecda65.jpeg",
    short: "Collagène liquide haute absorption — goût grenade, beauté visible.",
    desc: "NeoCell Collagen Peptides Liquid, collagène hydrolysé au délicieux goût grenade. Formule liquide haute absorption pour cheveux, peau et ongles. Sans gluten, sans OGM, sans soja ni produits laitiers. 473 ml.",
    benefits: [
      "Cheveux forts et brillants",
      "Peau éclatante et hydratée",
      "Ongles plus solides",
      "1 à 2 c. à soupe par jour — haute absorption",
    ],
  },
  {
    id: "dr-rashel-24k-tonique-essence",
    name: "Dr. Rashel 24K Gold Tonique Essence Anti-Taches",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 22900,
    badge: "Nouveau",
    image: "img/PHOTO-2026-08-26-21-36-15.jpg",
    short: "Tonique essence 24K Gold — éclat, uniformité et anti-taches.",
    desc: "Dr. Rashel 24K Gold Anti-Taches Tonique Essence. Enrichi en or 24K et actifs éclaircissants pour atténuer les taches brunes, unifier le teint et révéler l'éclat naturel. 300 ml — sans paraben, testé dermatologiquement.",
    benefits: [
      "Atténue les taches brunes",
      "Hydrate en profondeur",
      "Teint unifié et éclatant",
      "Convient à tous types de peaux",
    ],
  },
  {
    id: "dr-rashel-vitamin-e-dark-spots",
    name: "Dr. Rashel Vitamin E Dark Spots Corrector",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 21900,
    badge: "Nouveau",
    image: "img/PHOTO-2026-08-26-21-36-15 (1).jpg",
    short: "Sérum vitamine E — corrige les taches et unifie le teint.",
    desc: "Dr. Rashel Vitamin E Dark Spots Corrector. Enrichi en vitamine E et actifs éclaircissants pour réduire visiblement les taches, illuminer le teint et protéger la peau. 100 ml — texture légère, sans paraben.",
    benefits: [
      "Réduit visiblement les taches brunes",
      "Unifie le teint et illumine",
      "Antioxydant et protecteur",
      "Texture légère non grasse",
    ],
  },
  {
    id: "massa-ranee-savon-miel-propolis",
    name: "Massa Ranee Savon Miel & Propolis",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 14900,
    badge: "Nouveau",
    image: "img/PHOTO-2026-08-26-19-58-06 (1).jpg",
    short: "Savon naturel miel & propolis — peau nette, douce et éclatante.",
    desc: "Massa Ranee Savon Miel & Propolis. Formule naturelle au miel, propolis, huile d'olive et huile de coco. Idéal pour teint noir : éclat naturel, teint unifié, imperfections atténuées. Naturel & authentique.",
    benefits: [
      "Hydrate et nourrit en profondeur",
      "Purifie et protège la peau",
      "Unifie le teint",
      "Peau douce, saine et lumineuse",
    ],
  },
  {
    id: "cgn-hydrolyzed-collagen",
    name: "California Gold Collagène Hydrolysé",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 24900,
    badge: "Nouveau",
    image: "img/PHOTO-2026-08-29-08-49-30.jpg",
    short: "Peptides de collagène type I & III — peau ferme, cheveux et articulations.",
    desc: "California Gold Nutrition Hydrolyzed Collagen Peptides. 200 g, sans goût, haute absorption. 1 mesure (10 g) dans 200–250 ml d'eau ou boisson. Sans gluten, sans OGM, sans soja — testé par un tiers indépendant.",
    benefits: [
      "Améliore l'élasticité de la peau",
      "Hydrate et nourrit la peau",
      "Renforce cheveux et ongles",
      "Soutient articulations et os",
    ],
  },
  {
    id: "youtheory-collagen-vanilla",
    name: "youtheory Collagen Powder Vanille",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 26900,
    badge: "Nouveau",
    image: "img/PHOTO-2026-08-29-08-49-30 (1).jpg",
    short: "Poudre collagène vanille — peau, cheveux, ongles et articulations.",
    desc: "youtheory Collagen Powder saveur vanille. 133 g. 1 mesure (20 g) dans 200–250 ml d'eau, jus ou smoothie, une fois par jour. Sans gluten, sans OGM, sans colorants artificiels — testé en laboratoire.",
    benefits: [
      "Favorise l'élasticité de la peau",
      "Renforce cheveux et ongles",
      "Soutient la santé des articulations",
      "Saveur vanille délicieuse",
    ],
  },
  {
    id: "kal-stress-b-complex",
    name: "KAL Stress B-Complex",
    category: "energie",
    categoryLabel: "Énergie",
    price: 18900,
    badge: "Nouveau",
    image: "img/PHOTO-2026-08-29-08-49-30 (2).jpg",
    short: "Complexe vitamines B — énergie, concentration et gestion du stress.",
    desc: "KAL Stress B-Complex. 100 comprimés. Formule complète de vitamines B pour soutenir l'énergie naturelle, la concentration et aider à gérer le stress quotidien. 2 comprimés par jour, de préférence avec un repas.",
    benefits: [
      "Soutient l'énergie physique et mentale",
      "Favorise la concentration",
      "Aide à gérer le stress quotidien",
      "Réduit fatigue et épuisement",
    ],
  },
  {
    id: "21st-century-stress-b-zinc",
    name: "21st Century Stress B with Zinc",
    category: "energie",
    categoryLabel: "Énergie",
    price: 15900,
    badge: "Nouveau",
    image: "img/PHOTO-2026-08-29-08-49-30 (3).jpg",
    short: "Vitamines B + zinc — énergie, immunité et concentration.",
    desc: "21st Century Stress B with Zinc. 66 comprimés sans gluten. Bouclier naturel contre le stress : réduit la fatigue, booste l'énergie, renforce l'immunité et favorise la concentration. 1 comprimé par jour avec un repas.",
    benefits: [
      "Réduit la fatigue",
      "Booste l'énergie naturelle",
      "Renforce l'immunité",
      "Améliore la concentration",
    ],
  },
  {
    id: "cgn-l-arginine",
    name: "California Gold L-Arginine 500 mg",
    category: "homme",
    categoryLabel: "Homme",
    price: 17900,
    badge: "Nouveau",
    image: "img/ac48e233-9248-4817-9edd-62c786c3c53d.jpeg",
    short: "L-Arginine 500 mg — circulation, endurance et récupération.",
    desc: "California Gold Nutrition L-Arginine 500 mg. 60 gélules végétales. Soutient la circulation, l'endurance et la récupération musculaire. Sans gluten, sans soja — convient aux végétariens.",
    benefits: [
      "Améliore la circulation sanguine",
      "Soutient endurance et récupération",
      "Contribue à la santé cardiovasculaire",
      "Gélules végétales — sans gluten ni soja",
    ],
  },
  {
    id: "cgn-l-citrulline",
    name: "California Gold L-Citrulline 500 mg",
    category: "homme",
    categoryLabel: "Homme",
    price: 18900,
    badge: "Nouveau",
    image: "img/26a1e066-165c-4be9-adc1-53bc8d9fe29b.jpeg",
    short: "L-Citrulline Sport — endurance, circulation et récupération.",
    desc: "California Gold Nutrition SPORT L-Citrulline 500 mg. 60 gélules végétales. Favorise la production d'oxyde nitrique, soutient l'endurance à l'entraînement et la récupération musculaire. Sans gluten, OGM ni soja.",
    benefits: [
      "Soutient l'endurance à l'entraînement",
      "Favorise la circulation (oxyde nitrique)",
      "Aide à la récupération musculaire",
      "Formule premium sans gluten / OGM / soja",
    ],
  },
  {
    id: "beauty-of-joseon-glow-serum",
    name: "Beauty of Joseon Glow Serum Propolis + Niacinamide",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 24900,
    badge: "Nouveau",
    image: "img/2461fba7-cd20-4780-b994-685dae14bb1b.jpeg",
    short: "Sérum glow coréen — propolis & niacinamide pour une peau éclatante.",
    desc: "Beauty of Joseon Glow Serum : Propolis + Niacinamide. Hydrate en profondeur, illumine le teint, réduit l'apparence des pores et renforce la barrière cutanée. Texture légère non collante — tous types de peaux.",
    benefits: [
      "Hydrate en profondeur",
      "Illumine le teint",
      "Réduit l'apparence des pores",
      "Renforce la barrière cutanée",
    ],
  },
  {
    id: "beauty-of-joseon-calming-serum",
    name: "Beauty of Joseon Sérum Apaisant Thé Vert & Panthénol",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 23900,
    badge: "Nouveau",
    image: "img/7e7714c4-4b41-4023-806e-080ed042358a.jpeg",
    short: "Sérum apaisant thé vert + panthénol — calme et hydrate la peau.",
    desc: "Beauty of Joseon Calming Serum Green Tea + Panthenol. Apaise les rougeurs, hydrate en profondeur, renforce la barrière cutanée et aide à réduire les imperfections. Convient à tous les types de peau.",
    benefits: [
      "Apaise les rougeurs",
      "Hydrate en profondeur",
      "Renforce la barrière cutanée",
      "Aide à réduire les imperfections",
    ],
  },
  {
    id: "skin1004-centella-ampoule",
    name: "SKIN1004 Madagascar Centella Ampoule",
    category: "beaute",
    categoryLabel: "Beauté",
    price: 25900,
    badge: "Nouveau",
    image: "img/261078f1-6274-48fb-a1c5-becaed5c36f8.jpeg",
    short: "Ampoule Centella Asiatica 100 ml — éclat, hydratation et apaisement.",
    desc: "SKIN1004 Madagascar Centella Ampoule. Soin à la Centella Asiatica pure de Madagascar pour une peau plus nette, lisse et éclatante. Hydrate, apaise les irritations et améliore la texture. Sans parabène, sans alcool — non testé sur les animaux. 100 ml.",
    benefits: [
      "Révèle l'éclat du teint",
      "Hydrate en profondeur",
      "Apaise les irritations",
      "Améliore la texture de la peau",
    ],
  },
  {
    id: "mason-little-animals-multivitamins",
    name: "Mason Natural Little Animals Multivitamines",
    category: "enfants",
    categoryLabel: "Enfants",
    price: 14900,
    badge: "Nouveau",
    image: "img/fadb8e53-0370-4568-86ec-82bb5185e3ee.jpeg",
    short: "Multivitamines à croquer formes animaux — dès 2 ans, goût fruité.",
    desc: "Mason Natural Chewable Little Animals Multivitamins. 60 comprimés à croquer au goût fruité. Renforce l'immunité, favorise la croissance et la concentration. Sans colorants artificiels ni conservateurs — dès 2 ans.",
    benefits: [
      "Renforce le système immunitaire",
      "Favorise croissance et os",
      "Améliore concentration et mémoire",
      "Goût fruité — sans colorants artificiels",
    ],
  },
];

let PRODUCTS = FALLBACK_PRODUCTS;

async function loadProducts() {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 5000);
  try {
    const res = await fetch("api/products.php?action=list", {
      headers: { Accept: "application/json" },
      signal: controller.signal,
    });
    const data = await res.json();
    if (data.ok && Array.isArray(data.products) && data.products.length) {
      PRODUCTS = data.products;
    } else {
      PRODUCTS = FALLBACK_PRODUCTS;
    }
  } catch (err) {
    console.warn("API produits indisponible, catalogue local utilisé.", err);
    PRODUCTS = FALLBACK_PRODUCTS;
  } finally {
    clearTimeout(timeoutId);
  }
  window.PRODUCTS = PRODUCTS;
  return PRODUCTS;
}

window.loadProducts = loadProducts;
window.PRODUCTS = PRODUCTS;
